version: "3.9"

services:
  nodejs:
    build:
      target: dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    command: yarn serve
    volumes:
      - "./nodejs:/home/node/app"
